# Generated by Django 2.2 on 2019-06-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project4App', '0003_auto_20190603_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='text',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
