# Generated by Django 2.2 on 2019-06-03 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Project4App', '0004_auto_20190603_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='commentForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Project4App.Video'),
        ),
    ]
