# Generated by Django 2.2 on 2019-06-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project4App', '0006_auto_20190603_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ('created_date',)},
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='approved_comment',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
