# Generated by Django 2.2 on 2019-06-05 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project4App', '0007_auto_20190603_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='commenterForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Project4App.AccountModel'),
        ),
    ]
